#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version 0.10.

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_script_progression --message="Installing NodeJS..." --weight=10

# Install Nodejs
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version
ynh_use_nodejs

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
# ynh_script_progression --message="Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

# Create a dedicated systemd config
# ynh_add_systemd_config

# yunohost service add $app --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
# ynh_use_logrotate

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding app's configuration file..."

# ynh_add_config --template="" --destination="$install_dir/"

# FIXME: this should be handled by the core in the future
# You may need to use chmod 600 instead of 400,
# for example if the app is expected to be able to modify its own config
chmod 700 "$install_dir/"
chown $app:$app "$install_dir/"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression --message="Building frontend..." --weight=5

pushd $install_dir/build/web-frontend
    ynh_exec_as $app $ynh_node_load_PATH yarn install
    ynh_exec_as $app $ynh_node_load_PATH yarn cache clean
    ynh_exec_as $app env $ynh_node_load_PATH NUXT_TELEMETRY_DISABLED=1 yarn run build-local 
    ynh_secure_remove --file="$install_dir/build/web-frontend/node_modules"
    ynh_exec_as $app $ynh_node_load_PATH yarn install --production
    ynh_exec_as $app $ynh_node_load_PATH yarn cache clean
popd

mv $install_dir/build/web-frontend $install_dir
mv $install_dir/build/deploy/plugins $install_dir
ynh_replace_string --match_string="source /baserow" --replace_string="source $install_dir" --target_file="$install_dir/web-frontend/docker/docker-entrypoint.sh"

ynh_script_progression --message="Building backend..." --weight=5

ynh_exec_as $app python3 -m venv $install_dir/backend
source $install_dir/backend/bin/activate

mv $install_dir/build/backend $install_dir/backend/src
pip install -r $install_dir/backend/src/requirements/base.txt

ynh_replace_string --match_string="source /baserow" --replace_string="source $install_dir" --target_file="$install_dir/backend/src/backend/docker/docker-entrypoint.sh"

deactivate


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting app's systemd service..."

# Start a systemd service
# ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last